POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc1NTYxMTksInVzZXJJZCI6MX0.Hmd-dK_H2xddIiTSrG2bCE1hWNoorWOnPk3n327x7vk

{
  "name": "Test event ",
  "description": "test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}