PUT http://localhost:8080/events/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc1NTQ4ODUsInVzZXJJZCI6MX0.mku4e-Q9rdMeAIj38Ib-x-GphlxvIZen0zwZl3LWVtE

{
  "name": "Updated test event",
  "description": "A test event",
  "location": "Test location (Updated!)",
  "dateTime": "2025-01-01T15:30:00Z"
}